import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Layout from '../components/layout'
import ArticleProvider from '../components/ArticleProvider'
import UserProvider from '../components/UserProvider'
import { SessionProvider } from "next-auth/react"
import Head from 'next/head'
import { RecoilRoot } from 'recoil'

export default function App({ Component, pageProps: { session, ...pageProps } }: AppProps) {
  return (
    <RecoilRoot>
      <SessionProvider session={session}>
        <UserProvider>
          <ArticleProvider>
            <Layout>
                <Head>
                  <title>Woodsy</title>
                  <meta name="description" content="Generated by create next app" />
                  <meta name="viewport" content="width=device-width, initial-scale=1" />
                  <link rel="icon" href="/favicon.ico" />
                </Head>
                <Component {...pageProps} />
            </Layout>
          </ArticleProvider>
        </UserProvider>
      </SessionProvider>
    </RecoilRoot>
  )
}
